import { Nunito } from "next/font/google";
import "./globals.css";
import "../app/styles/bootstrap.min.css";
import "../app/styles/animate.min.css";
import "../app/styles/boxicons.min.css";
import "../app/styles/meanmenu.min.css";
import "../app/styles/flaticon.css";
import "../app/styles/flaticon.css";
import "react-modal-video/css/modal-video.min.css";
import "react-accessible-accordion/dist/fancy-example.css";
import "react-tabs/style/react-tabs.css";
import "react-18-image-lightbox/style.css";
import "swiper/css";
import "swiper/css/bundle";
// Global Styles
import "../app/styles/style.css";
// Global Responsive Styles
import "../app/styles/responsive.css";
// Global Dashboard Styles
import "../app/styles/dashboard.css";

import TosterProvider from "@/providers/TosterProvider";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import { getCurrentUser } from "@/actions/getCurrentUser";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
	title: "eDemy - React Next.js Education LMS Template",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	const currentUser = await getCurrentUser();
	return (
		<html lang="en">
			<body className={nunito.className} suppressHydrationWarning={true}>
				<TosterProvider />
				<Navbar currentUser={currentUser} />
				{children}
				<Footer />
			</body>
		</html>
	);
}
